---
- job:
    name: gh-role-linter
    run: tests/basic.yml

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - tox-linters
        - gh-role-linter
    gate:
      jobs:
        - tox-linters
#        - ansible-playbook playbooks/run.yml -e github_repos_state=present
