---
- project:
    merge-mode: squash-merge
    check:
      jobs:
        - tox-linters
        - ansible-playbook tests/basic.yml
    gate:
      jobs:
        - tox-linters
        # ansible-playbook playbooks/run.yml -e github_repos_state=present
