---
- job:
    name: ansible-test-simpleton
    attempts: 1
    pre-run: playbooks/simpleton/pre.yaml
    run: playbooks/simpleton/run.yaml
    vars:
      simple_source_image: "ansible:latest"
      simple_run:
        - ansible-playbook tests/basic.yml

- project:
    merge-mode: squash-merge
    check:
      jobs:
        - tox-linters
        - ansible-test-simpleton
    gate:
      jobs:
        - tox-linters
#        - ansible-playbook playbooks/run.yml -e github_repos_state=present
