---
- project:
    merge-mode: squash-merge
    check:
      jobs:
        - tox-linters
        - job:
            name: basic test for checks orgs data
            run: tests/basic.yml
    gate:
      jobs:
        - tox-linters
#        - ansible-playbook playbooks/run.yml -e github_repos_state=present
