---
- name: "Update teams in {{ org.key }}"
    script: >
      github_api.py --endpoint teams
      --org "{{ org.key }}" --teams "{{ org.value.teams }}"
    args:
      executable: python3
    register: failed_team_members