---

- name: Prepare github config
  hosts: localhost
  tasks:
    - name: Gather orgs info
      scan_organizations:
      register: structure

    - name: Register
      set_fact:
        orgs: "{{ structure }}"

- name: Manage orgs
  hosts: localhost
  gather_facts: no
  roles:
    - gitcontrol
  environment:
    github_user: "{{ lookup('env', 'GITHUB_USER') }}"
    github_token: "{{ lookup('env', 'GITHUB_TOKEN') }}"